### ISSUE TITLE
SFML Library

### ISSUE THREAD

**Issue by justinbax** [Antimeuh2433/b-l-o-c-k-s#4]
Can't load SFML library with traditional use of
```c++
#include <SFML/Graphics>
```
Problem is avoided by using tutorial SFML project provided by SFML, but this still needs to be fixed

**Comment by ChrisYx511** [comment]
¯\_(ツ)_/¯

**Comment by ChrisYx511** [comment]
worked on

**Comment by ChrisYx511** [comment]
completed in new build
