### ISSUE TITLE
Fix the Main.cpp

### ISSUE THREAD

**Issue by ChrisYx511** [Antimeuh2433/b-l-o-c-k-s#8]
![image](https://user-images.githubusercontent.com/58494380/70875316-8e7db000-1f83-11ea-91fb-6248b0a9617c.png)
well this

**Comment by justinbax** [comment]
Project is up to date
No problem in my compiler, can build and launch project normally
idk wtf
<img width="1440" alt="Screen Shot 2019-12-16 at 6 45 31 PM" src="https://user-images.githubusercontent.com/29051011/70952480-57b3a280-2034-11ea-99ec-d9c09905c3cc.png">

**Comment by ChrisYx511** [comment]
*confused screaming*

**Comment by ChrisYx511** [comment]
can you send your compiler versions and stuff

**Comment by justinbax** [comment]
> can you send your compiler versions and stuff

you gotta explain how to see it ik i'm a d u m b a s s
but all I can tell is
Visual Studio Code
Version: 1.41.0
Commit: 9579eda04fdb3a9bba2750f15193e5fafe16b959
Date: 2019-12-11T17:58:38.338Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 17.7.0
(app info on mac: Code > About Visual Studio Code)

**Comment by ChrisYx511** [comment]
ok so you should be using clang and I chose to use G++ instead of gcc default on Linux. Might be a platform thing or a compiler thing.
I also tried running the makefile manually it still doesn't work
![image](https://user-images.githubusercontent.com/58494380/70957639-c26cda00-2044-11ea-9ea6-840d77817925.png)

**Comment by justinbax** [comment]
can it build+run now? I see you did some work with compiler stuff so yeah

**Comment by ChrisYx511** [comment]
should be fixed with new build

**Comment by ChrisYx511** [comment]
fixed in new build
